In [1]:
import pandas as pd

In [2]:
dictionary = {"Matematica" : [6, 7, 8], "Inglese" : [4.5, 8, 6]}

In [3]:
data = pd.DataFrame(dictionary) #Crea un dataframe a partire da un dizionario

In [4]:
data

   Matematica  Inglese
0           6      4.5
1           7      8.0
2           8      6.0

In [5]:
data.to_html("prova.html")

In [6]:
data = pd.read_csv("Fuel_Consumption_2000-2022.csv")

In [7]:
data

,YEAR,MAKE,MODEL,VEHICLE CLASS,ENGINE SIZE,CYLINDERS,TRANSMISSION,FUEL,FUEL CONSUMPTION,HWY (L/100 KM),COMB (L/100 KM),COMB (MPG),EMISSIONS
0,2000,ACURA,1.6EL,COMPACT,1.6,4,A4,X,9.2,6.7,8.1,35,186
1,2000,ACURA,1.6EL,COMPACT,1.6,4,M5,X,8.5,6.5,7.6,37,175
2,2000,ACURA,3.2TL,MID-SIZE,3.2,6,AS5,Z,12.2,7.4,10.0,28,230
3,2000,ACURA,3.5RL,MID-SIZE,3.5,6,A4,Z,13.4,9.2,11.5,25,264
4,2000,ACURA,INTEGRA,SUBCOMPACT,1.8,4,A4,X,10.0,7.0,8.6,33,198
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22551,2022,VOLVO,XC40 T5 AWD,SUV: SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
22552,2022,VOLVO,XC60 B5 AWD,SUV: SMALL,2.0,4,AS8,Z,10.5,8.1,9.4,30,219
22553,2022,VOLVO,XC60 B6 AWD,SUV: SMALL,2.0,4,AS8,Z,11.0,8.7,9.9,29,232
22554,2022,VOLVO,XC90 T5 AWD,SUV: STANDARD,2.0,4,AS8,Z,11.5,8.4,10.1,28,236
22555,2022,VOLVO,XC90 T6 AWD,SUV: STANDARD,2.0,4,AS8,Z,12.4,8.9,10.8,26,252

## Selezionare colonne

In [8]:
data["MAKE"]  #colonna marca -> data[nomeColonna]

0        ACURA
1        ACURA
2        ACURA
3        ACURA
4        ACURA
         ...
22551    VOLVO
22552    VOLVO
22553    VOLVO
22554    VOLVO
22555    VOLVO
Name: MAKE, Length: 22556, dtype: object

In [9]:
data["MAKE"].values #colonna marca in array numpy

array(['ACURA', 'ACURA', 'ACURA', ..., 'VOLVO', 'VOLVO', 'VOLVO'],
      dtype=object)

In [10]:
data[["MAKE", "FUEL", "EMISSIONS"]] #piÃ¹ colonne

        MAKE FUEL  EMISSIONS
0      ACURA    X        186
1      ACURA    X        175
2      ACURA    Z        230
3      ACURA    Z        264
4      ACURA    X        198
...      ...  ...        ...
22551  VOLVO    Z        219
22552  VOLVO    Z        219
22553  VOLVO    Z        232
22554  VOLVO    Z        236
22555  VOLVO    Z        252

[22556 rows x 3 columns]

In [11]:
array = data[["MAKE", "FUEL", "EMISSIONS"]].values #matrice delle colonne

In [12]:
array.shape

(22556, 3)

## Selezionare righe

In [13]:
data[data["MAKE"] == "VOLVO"]

,YEAR,MAKE,MODEL,VEHICLE CLASS,ENGINE SIZE,CYLINDERS,TRANSMISSION,FUEL,FUEL CONSUMPTION,HWY (L/100 KM),COMB (L/100 KM),COMB (MPG),EMISSIONS
618,2000,VOLVO,C70 CONVERTIBLE TURBO,SUBCOMPACT,2.3,5,A4,Z,12.6,8.7,10.8,26,248
619,2000,VOLVO,C70 CONVERTIBLE TURBO,SUBCOMPACT,2.3,5,M5,Z,11.9,8.2,10.2,28,235
620,2000,VOLVO,C70 CONVERTIBLE TURBO,SUBCOMPACT,2.4,5,A4,Z,12.4,8.3,10.6,27,244
621,2000,VOLVO,C70 TURBO,COMPACT,2.3,5,A4,Z,12.4,8.0,10.4,27,239
622,2000,VOLVO,C70 TURBO,COMPACT,2.3,5,M5,Z,11.5,7.8,9.8,29,225
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22551,2022,VOLVO,XC40 T5 AWD,SUV: SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
22552,2022,VOLVO,XC60 B5 AWD,SUV: SMALL,2.0,4,AS8,Z,10.5,8.1,9.4,30,219
22553,2022,VOLVO,XC60 B6 AWD,SUV: SMALL,2.0,4,AS8,Z,11.0,8.7,9.9,29,232
22554,2022,VOLVO,XC90 T5 AWD,SUV: STANDARD,2.0,4,AS8,Z,11.5,8.4,10.1,28,236
22555,2022,VOLVO,XC90 T6 AWD,SUV: STANDARD,2.0,4,AS8,Z,12.4,8.9,10.8,26,252

In [14]:
volvo_200 = data[(data["MAKE"] == "VOLVO") & (data["EMISSIONS"] <= 200)].copy()
volvo_200

,YEAR,MAKE,MODEL,VEHICLE CLASS,ENGINE SIZE,CYLINDERS,TRANSMISSION,FUEL,FUEL CONSUMPTION,HWY (L/100 KM),COMB (L/100 KM),COMB (MPG),EMISSIONS
9970,2010,VOLVO,C30 T5,COMPACT,2.5,5,AS5,X,10.2,6.8,8.7,32,200
9971,2010,VOLVO,C30 T5,COMPACT,2.5,5,M6,X,10.2,6.8,8.7,32,200
9976,2010,VOLVO,S40 T5,COMPACT,2.5,5,AS5,X,10.2,6.8,8.7,32,200
9977,2010,VOLVO,S40 T5,COMPACT,2.5,5,M6,X,10.2,6.8,8.7,32,200
9985,2010,VOLVO,V50 T5,STATION WAGON - SMALL,2.5,5,AS5,X,10.2,6.8,8.7,32,200
9986,2010,VOLVO,V50 T5,STATION WAGON - SMALL,2.5,5,M6,X,10.2,6.8,8.7,32,200
11057,2011,VOLVO,C30 T5,COMPACT,2.5,5,AS5,X,10.1,6.6,8.6,33,198
11058,2011,VOLVO,C30 T5,COMPACT,2.5,5,M6,X,10.2,6.8,8.7,32,200
11061,2011,VOLVO,S40 T5,COMPACT,2.5,5,AS5,X,10.1,6.6,8.6,33,198
11065,2011,VOLVO,V50 T5,STATION WAGON - SMALL,2.5,5,AS5,X,10.1,6.6,8.6,33,198
12140,2012,VOLVO,C30 T5,COMPACT,2.5,5,AS5,X,10.1,6.6,8.6,33,198
12141,2012,VOLVO,C30 T5,COMPACT,2.5,5,M6,X,10.2,6.8,8.7,32,200
13199,2013,VOLVO,C30,COMPACT,2.5,5,AS5,X,10.1,6.6,8.6,33,198
13200,2013,VOLVO,C30,COMPACT,2.5,5,M6,X,10.2,6.8,8.7,32,200
13202,2013,VOLVO,S60,COMPACT,2.5,5,AS6,X,9.9,6.5,8.4,34,193
14242,2014,VOLVO,S60,COMPACT,2.5,5,AS6,X,9.9,6.5,8.4,34,193
15365,2015,VOLVO,S60 T5,COMPACT,2.0,4,AS8,X,9.8,6.6,8.4,34,193
15369,2015,VOLVO,S80 T5,MID-SIZE,2.0,4,AS8,X,9.8,6.6,8.4,34,193
15374,2015,VOLVO,V60 T5,STATION WAGON - SMALL,2.0,4,AS8,X,9.8,6.6,8.4,34,193
16470,2016,VOLVO,S60 INSCRIPTION,COMPACT,2.0,4,AS8,X,9.6,6.7,8.3,34,193
16472,2016,VOLVO,S60 T5,COMPACT,2.0,4,AS8,X,9.6,6.7,8.3,34,193
16478,2016,VOLVO,S80 T5,MID-SIZE,2.0,4,AS8,X,9.6,6.7,8.3,34,193
16480,2016,VOLVO,V60 T5,STATION WAGON - SMALL,2.0,4,AS8,X,9.6,6.7,8.3,34,193
17530,2017,VOLVO,S60 T5,COMPACT,2.0,4,AS8,X,9.6,7.0,8.4,34,198
17532,2017,VOLVO,S60 INSCRIPTION T5,COMPACT,2.0,4,AS8,X,9.6,7.0,8.4,34,198
17539,2017,VOLVO,V60 T5,STATION WAGON - SMALL,2.0,4,AS8,X,9.6,7.0,8.4,34,198
19678,2019,VOLVO,S60 T5,COMPACT,2.0,4,AS8,Z,9.9,6.6,8.4,34,197
19682,2019,VOLVO,V60 T5,STATION WAGON: SMALL,2.0,4,AS8,Z,9.9,6.6,8.4,34,197
21588,2021,VOLVO,S60 T5,COMPACT,2.0,4,AS8,Z,10.0,6.8,8.6,33,200
21592,2021,VOLVO,V60 T5,STATION WAGON: SMALL,2.0,4,AS8,Z,10.0,6.8,8.6,33,200
22544,2022,VOLVO,S60 B5,COMPACT,2.0,4,AS8,Z,9.0,6.7,8.0,35,186
22545,2022,VOLVO,S60 B5 AWD,COMPACT,2.0,4,AS8,Z,9.4,6.9,8.3,34,193

In [15]:
volvo_200[["FUEL", "FUEL CONSUMPTION", "EMISSIONS"]]

      FUEL  FUEL CONSUMPTION  EMISSIONS
9970     X              10.2        200
9971     X              10.2        200
9976     X              10.2        200
9977     X              10.2        200
9985     X              10.2        200
9986     X              10.2        200
11057    X              10.1        198
11058    X              10.2        200
11061    X              10.1        198
11065    X              10.1        198
12140    X              10.1        198
12141    X              10.2        200
13199    X              10.1        198
13200    X              10.2        200
13202    X               9.9        193
14242    X               9.9        193
15365    X               9.8        193
15369    X               9.8        193
15374    X               9.8        193
16470    X               9.6        193
16472    X               9.6        193
16478    X               9.6        193
16480    X               9.6        193
17530    X               9.6        198
17532    X               9.6        198
17539    X               9.6        198
19678    Z               9.9        197
19682    Z               9.9        197
21588    Z              10.0        200
21592    Z              10.0        200
22544    Z               9.0        186
22545    Z               9.4        193

## Funzione di aggregazione

In [16]:
data["EMISSIONS"].max()

608

In [17]:
data["EMISSIONS"].count()

22556

In [18]:
data["EMISSIONS"].mean()

250.06845185316544

In [19]:
data["EMISSIONS"].std()

59.355276326282905

In [20]:
data[data["MAKE"] == "VOLVO"]["EMISSIONS"].max()

315

In [21]:
data["MAKE"].unique() #Valori univoci -- distinct

array(['ACURA', 'AUDI', 'BMW', 'BUICK', 'CADILLAC', 'CHEVROLET',
       'CHRYSLER', 'DAEWOO', 'DODGE', 'FERRARI', 'FORD', 'GMC', 'HONDA',
       'HYUNDAI', 'INFINITI', 'ISUZU', 'JAGUAR', 'JEEP', 'KIA',
       'LAND ROVER', 'LEXUS', 'LINCOLN', 'MAZDA', 'MERCEDES-BENZ',
       'NISSAN', 'OLDSMOBILE', 'PLYMOUTH', 'PONTIAC', 'PORSCHE', 'SAAB',
       'SATURN', 'SUBARU', 'SUZUKI', 'TOYOTA', 'VOLKSWAGEN', 'VOLVO',
       'BENTLEY', 'ROLLS-ROYCE', 'MASERATI', 'MINI', 'MITSUBISHI',
       'SMART', 'HUMMER', 'ASTON MARTIN', 'LAMBORGHINI', 'BUGATTI',
       'SCION', 'FIAT', 'RAM', 'SRT', 'ALFA ROMEO', 'GENESIS'],
      dtype=object)

In [22]:
data["FUEL"].unique()

array(['X', 'Z', 'E', 'N', 'D'], dtype=object)

In [23]:
data[data["MAKE"] == "AUDI"]["TRANSMISSION"].unique()

array(['A5', 'M5', 'M6', 'AV', 'AS5', 'AS6', 'AS7', 'AS8', 'AM6', 'AV8',
       'AM7', 'A7', 'A6', 'AM8'], dtype=object)

In [24]:
data[["MAKE", "FUEL CONSUMPTION"]].groupby("MAKE").mean()   #group by, una colonna che raggruppo e una che aggrego

               FUEL CONSUMPTION
MAKE
ACURA                 10.937652
ALFA ROMEO            11.104762
ASTON MARTIN          17.026415
AUDI                  12.496894
BENTLEY               19.685593
BMW                   12.730537
BUGATTI               27.650000
BUICK                 12.182051
CADILLAC              13.696313
CHEVROLET             14.352019
CHRYSLER              12.698824
DAEWOO                10.535294
DODGE                 15.147459
FERRARI               21.683562
FIAT                   8.842353
FORD                  13.569026
GENESIS               13.495238
GMC                   16.188357
HONDA                  9.381640
HUMMER                16.390476
HYUNDAI               10.052941
INFINITI              12.596071
ISUZU                 14.888889
JAGUAR                13.376374
JEEP                  12.529963
KIA                   10.142669
LAMBORGHINI           21.001802
LAND ROVER            15.174713
LEXUS                 11.676087
LINCOLN               13.361333
MASERATI              16.636800
MAZDA                 10.468771
MERCEDES-BENZ         13.721787
MINI                   8.820690
MITSUBISHI            10.577640
NISSAN                11.511649
OLDSMOBILE            12.132353
PLYMOUTH              13.800000
PONTIAC               11.082213
PORSCHE               12.787854
RAM                   14.760131
ROLLS-ROYCE           19.346226
SAAB                  12.201053
SATURN                10.721154
SCION                  8.797727
SMART                  5.972727
SRT                   18.100000
SUBARU                10.757308
SUZUKI                10.072864
TOYOTA                10.644555
VOLKSWAGEN            10.284023
VOLVO                 11.637282

In [25]:
data[["MAKE", "FUEL CONSUMPTION", "EMISSIONS"]].groupby("MAKE").mean()

               FUEL CONSUMPTION   EMISSIONS
MAKE
ACURA                 10.937652  219.599190
ALFA ROMEO            11.104762  228.119048
ASTON MARTIN          17.026415  332.188679
AUDI                  12.496894  247.595031
BENTLEY               19.685593  375.652542
BMW                   12.730537  250.785235
BUGATTI               27.650000  538.250000
BUICK                 12.182051  232.047619
CADILLAC              13.696313  264.313364
CHEVROLET             14.352019  269.999531
CHRYSLER              12.698824  236.108235
DAEWOO                10.535294  204.000000
DODGE                 15.147459  283.115676
FERRARI               21.683562  411.000000
FIAT                   8.842353  184.364706
FORD                  13.569026  260.672274
GENESIS               13.495238  275.928571
GMC                   16.188357  301.874724
HONDA                  9.381640  191.475936
HUMMER                16.390476  317.952381
HYUNDAI               10.052941  204.226381
INFINITI              12.596071  251.910714
ISUZU                 14.888889  299.222222
JAGUAR                13.376374  261.063187
JEEP                  12.529963  254.479779
KIA                   10.142669  207.947368
LAMBORGHINI           21.001802  404.567568
LAND ROVER            15.174713  301.327586
LEXUS                 11.676087  236.817391
LINCOLN               13.361333  261.693333
MASERATI              16.636800  327.752000
MAZDA                 10.468771  212.171096
MERCEDES-BENZ         13.721787  273.270376
MINI                   8.820690  180.445813
MITSUBISHI            10.577640  213.366460
NISSAN                11.511649  234.828534
OLDSMOBILE            12.132353  235.088235
PLYMOUTH              13.800000  272.500000
PONTIAC               11.082213  214.407115
PORSCHE               12.787854  256.073887
RAM                   14.760131  286.457516
ROLLS-ROYCE           19.346226  372.528302
SAAB                  12.201053  234.521053
SATURN                10.721154  210.064103
SCION                  8.797727  179.840909
SMART                  5.972727  128.590909
SRT                   18.100000  345.000000
SUBARU                10.757308  217.830769
SUZUKI                10.072864  204.592965
TOYOTA                10.644555  219.758242
VOLKSWAGEN            10.284023  207.523538
VOLVO                 11.637282  230.143689

In [26]:
query = data[["MAKE", "FUEL", "FUEL CONSUMPTION", "EMISSIONS"]].groupby(["MAKE", "FUEL"]).mean()  #Due dati nel group by
query

                   FUEL CONSUMPTION   EMISSIONS
MAKE         FUEL
ACURA        X             8.815789  177.789474
             Z            11.323445  227.200957
ALFA ROMEO   Z            11.104762  228.119048
ASTON MARTIN Z            17.026415  332.188679
AUDI         D             9.836364  226.090909
...                             ...         ...
VOLKSWAGEN   E            17.300000  232.000000
             X            10.129321  204.216049
             Z            11.111254  219.668810
VOLVO        X            11.549133  228.150289
             Z            11.681871  231.152047

[120 rows x 2 columns]

In [31]:
data[["MAKE", "FUEL"]].value_counts() #Aggregazione utile per i conteggi

MAKE           FUEL
CHEVROLET      X       1495
BMW            Z       1461
FORD           X       1444
MERCEDES-BENZ  Z       1221
PORSCHE        Z        986
                       ...
PLYMOUTH       Z          2
OLDSMOBILE     Z          1
VOLKSWAGEN     E          1
MAZDA          D          1
SATURN         E          1
Length: 120, dtype: int64

In [32]:
data["ENGINE SIZE CM3"] = data["ENGINE SIZE"] * 1000
data

,YEAR,MAKE,MODEL,VEHICLE CLASS,ENGINE SIZE,CYLINDERS,TRANSMISSION,FUEL,FUEL CONSUMPTION,HWY (L/100 KM),COMB (L/100 KM),COMB (MPG),EMISSIONS,ENGINE SIZE CM3
0,2000,ACURA,1.6EL,COMPACT,1.6,4,A4,X,9.2,6.7,8.1,35,186,1600.0
1,2000,ACURA,1.6EL,COMPACT,1.6,4,M5,X,8.5,6.5,7.6,37,175,1600.0
2,2000,ACURA,3.2TL,MID-SIZE,3.2,6,AS5,Z,12.2,7.4,10.0,28,230,3200.0
3,2000,ACURA,3.5RL,MID-SIZE,3.5,6,A4,Z,13.4,9.2,11.5,25,264,3500.0
4,2000,ACURA,INTEGRA,SUBCOMPACT,1.8,4,A4,X,10.0,7.0,8.6,33,198,1800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22551,2022,VOLVO,XC40 T5 AWD,SUV: SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219,2000.0
22552,2022,VOLVO,XC60 B5 AWD,SUV: SMALL,2.0,4,AS8,Z,10.5,8.1,9.4,30,219,2000.0
22553,2022,VOLVO,XC60 B6 AWD,SUV: SMALL,2.0,4,AS8,Z,11.0,8.7,9.9,29,232,2000.0
22554,2022,VOLVO,XC90 T5 AWD,SUV: STANDARD,2.0,4,AS8,Z,11.5,8.4,10.1,28,236,2000.0
22555,2022,VOLVO,XC90 T6 AWD,SUV: STANDARD,2.0,4,AS8,Z,12.4,8.9,10.8,26,252,2000.0